### ISSUE TITLE
Error: rsk3.js is not working with node version 8

### ISSUE THREAD

**Issue by jonathansmirnoff** [rsksmart/rsk3.js#53]
If it is used node version 8 for the package `@rsksmart/rsk3-account` it is get the following error:

```
Error: Cannot find module 'scrypt-shim'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/.../Documents/code/utils/node_modules/@rsksmart/rsk3-account/dist/@rsksmart/rsk3-account.cjs.js:25:30)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
```

**I suggest two options**:
- **Fix the issue**
- **Require at least node 10 for running it**.

**Comment by chrisli30** [comment]
@jonathansmirnoff You are right. This error is caused by package dependency.

@tinyyxx Could you confirm that the error occurs in node 8.6.0, and figure out what node version is compatible with it?

You need to change the "engine" keyword in package.json

**Comment by tinyyxx** [comment]
# node 8.6.0 occurs this error
![image](https://user-images.githubusercontent.com/13350957/86917060-16f9b300-c157-11ea-8f9a-0b7f03660649.png)

# node 10.13.0 can work
![image](https://user-images.githubusercontent.com/13350957/86923952-5a591f00-c161-11ea-8461-0daa52c1cbde.png)

**Comment by tinyyxx** [comment]
@jonathansmirnoff 
Yes, this package require at least node 10 for running it, I already made a pull request about demanded version
